sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dockerhub88/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dockerhub88/react-test npm test

after_success:
  - docker build -t dockerhub88/multi-client ./client
  - docker build -t dockerhub88/multi-nginx ./nginx
  - docker build -t dockerhub88/multi-server ./server
  - docker build -t dockerhub88/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push dockerhub88/multi-client
  - docker push dockerhub88/multi-nginx 
  - docker push dockerhub88/multi-server
  - docker push dockerhub88/multi-worker

deploy:
 provider: elasticbeanstalk
 region: "us-east-2" 
 app: "multi-docker"
 env: "MultiDocker-env"
 bucket_name: "elasticbeanstalk-us-east-2-697460064223"
 bucket_path: "docker-multi"
 on:
     branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_KEY